name: Release Artifact Automation

on:
  release:
    types: [published]

jobs:
  attach-artifact:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to upload release assets

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Archive release artifact
        run: zip release-asset.zip artifact.txt

      - name: Upload asset to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: release-asset.zip
